export const mainTeams = [
  { name: "Manchester City FC", id: 65, country: "England" },
  { name: "Manchester United FC", id: 66, country: "England" },
  { name: "Leicester City FC", id: 338, country: "England" },
  { name: "Chelsea FC", id: 61, country: "England" },
  { name: "Tottenham Hotspur FC", id: 73, country: "England" },
  { name: "Liverpool FC", id: 64, country: "England" },
  { name: "Everton FC", id: 62, country: "England" },
  { name: "Arsenal FC", id: 57, country: "England" },
  { name: "Club Atlético de Madrid", id: 78, country: "Spain" },
  { name: "FC Barcelona", id: 81, country: "Spain" },
  { name: "Real Madrid CF", id: 86, country: "Spain" },
  { name: "Sevilla FC", id: 559, country: "Spain" },
  { name: "Paris Saint-Germain FC", id: 524, country: "France" },
  { name: "AS Monaco FC", id: 548, country: "France" },
  { name: "Olympique Lyonnais", id: 523, country: "France" },
  { name: "Olympique de Marseille", id: 516, country: "France" },
  { name: "FC Bayern München", id: 5, country: "Germany" },
  { name: "RB Leipzig", id: 721, country: "Germany" },
  { name: "Borussia Dortmund", id: 4, country: "Germany" },
  { name: "Bayer 04 Leverkusen", id: 3, country: "Germany" },
  { name: "FC Internazionale Milano", id: 108, country: "Italy" },
  { name: "Atalanta BC", id: 102, country: "Italy" },
  { name: "Juventus FC", id: 109, country: "Italy" },
  { name: "AC Milan", id: 98, country: "Italy" },
  { name: "SSC Napoli", id: 113, country: "Italy" },
  { name: "SS Lazio", id: 110, country: "Italy" },
  { name: "AS Roma", id: 100, country: "Italy" },
  { name: "Sporting Clube de Portugal", id: 498, country: "Portugal" },
  { name: "FC Porto", id: 503, country: "Portugal" },
  { name: "Sport Lisboa e Benfica", id: 1903, country: "Portugal" },
  { name: "AFC Ajax", id: 678, country: "Netherlands" },
  { name: "PSV", id: 674, country: "Netherlands" },
  { name: "Norwich City FC", id: 68, country: "England" },
  { name: "Watford FC", id: 346, country: "England" },
  { name: "AFC Bournemouth", id: 1044, country: "England" },
];
