export const teams = [
  { name: "Manchester City FC", id: 65 },
  { name: "Manchester United FC", id: 66 },
  { name: "Leicester City FC", id: 338 },
  { name: "Chelsea FC", id: 61 },
  { name: "West Ham United FC", id: 563 },
  { name: "Tottenham Hotspur FC", id: 73 },
  { name: "Liverpool FC", id: 64 },
  { name: "Everton FC", id: 62 },
  { name: "Arsenal FC", id: 57 },
  { name: "Aston Villa FC", id: 58 },
  { name: "Leeds United FC", id: 341 },
  { name: "Wolverhampton Wanderers FC", id: 76 },
  { name: "Newcastle United FC", id: 67 },
  { name: "Crystal Palace FC", id: 354 },
  { name: "Brighton &amp; Hove Albion FC", id: 397 },
  { name: "Southampton FC", id: 340 },
  { name: "Burnley FC", id: 328 },
  { name: "Fulham FC", id: 63 },
  { name: "West Bromwich Albion FC", id: 74 },
  { name: "Sheffield United FC", id: 356 },
  { name: "Club Atlético de Madrid", id: 78 },
  { name: "FC Barcelona", id: 81 },
  { name: "Real Madrid CF", id: 86 },
  { name: "Sevilla FC", id: 559 },
  { name: "Real Sociedad de Fútbol", id: 92 },
  { name: "Villarreal CF", id: 94 },
  { name: "Real Betis Balompié", id: 90 },
  { name: "Athletic Club", id: 77 },
  { name: "Granada CF", id: 83 },
  { name: "RC Celta de Vigo", id: 558 },
  { name: "CA Osasuna", id: 79 },
  { name: "Cádiz CF", id: 264 },
  { name: "Levante UD", id: 88 },
  { name: "Valencia CF", id: 95 },
  { name: "Getafe CF", id: 82 },
  { name: "Real Valladolid CF", id: 250 },
  { name: "Deportivo Alavés", id: 263 },
  { name: "SD Huesca", id: 299 },
  { name: "Elche CF", id: 285 },
  { name: "SD Eibar", id: 278 },
  { name: "Lille OSC", id: 521 },
  { name: "Paris Saint-Germain FC", id: 524 },
  { name: "AS Monaco FC", id: 548 },
  { name: "Olympique Lyonnais", id: 523 },
  { name: "Racing Club de Lens", id: 546 },
  { name: "Olympique de Marseille", id: 516 },
  { name: "Stade Rennais FC 1901", id: 529 },
  { name: "Montpellier HSC", id: 518 },
  { name: "FC Metz", id: 545 },
  { name: "OGC Nice", id: 522 },
  { name: "Stade de Reims", id: 547 },
  { name: "AS Saint-Étienne", id: 527 },
  { name: "Angers SCO", id: 532 },
  { name: "Stade Brestois 29", id: 512 },
  { name: "FC Girondins de Bordeaux", id: 526 },
  { name: "RC Strasbourg Alsace", id: 576 },
  { name: "FC Lorient", id: 525 },
  { name: "FC Nantes", id: 543 },
  { name: "Nîmes Olympique", id: 556 },
  { name: "Dijon Football Côte d'Or", id: 528 },
  { name: "FC Bayern München", id: 5 },
  { name: "RB Leipzig", id: 721 },
  { name: "VfL Wolfsburg", id: 11 },
  { name: "Eintracht Frankfurt", id: 19 },
  { name: "Borussia Dortmund", id: 4 },
  { name: "Bayer 04 Leverkusen", id: 3 },
  { name: "Borussia Mönchengladbach", id: 18 },
  { name: "1. FC Union Berlin", id: 28 },
  { name: "VfB Stuttgart", id: 10 },
  { name: "SC Freiburg", id: 17 },
  { name: "TSG 1899 Hoffenheim", id: 2 },
  { name: "1. FSV Mainz 05", id: 15 },
  { name: "FC Augsburg", id: 16 },
  { name: "Hertha BSC", id: 9 },
  { name: "SV Werder Bremen", id: 12 },
  { name: "Arminia Bielefeld", id: 38 },
  { name: "1. FC Köln", id: 1 },
  { name: "FC Schalke 04", id: 6 },
  { name: "FC Internazionale Milano", id: 108 },
  { name: "Atalanta BC", id: 102 },
  { name: "Juventus FC", id: 109 },
  { name: "AC Milan", id: 98 },
  { name: "SSC Napoli", id: 113 },
  { name: "SS Lazio", id: 110 },
  { name: "AS Roma", id: 100 },
  { name: "US Sassuolo Calcio", id: 471 },
  { name: "UC Sampdoria", id: 584 },
  { name: "Hellas Verona FC", id: 450 },
  { name: "Udinese Calcio", id: 115 },
  { name: "Bologna FC 1909", id: 103 },
  { name: "Genoa CFC", id: 107 },
  { name: "ACF Fiorentina", id: 99 },
  { name: "Torino FC", id: 586 },
  { name: "Spezia Calcio", id: 488 },
  { name: "Cagliari Calcio", id: 104 },
  { name: "Benevento Calcio", id: 1106 },
  { name: "Parma Calcio 1913", id: 112 },
  { name: "FC Crotone", id: 472 },
  { name: "Sporting Clube de Portugal", id: 498 },
  { name: "FC Porto", id: 503 },
  { name: "Sport Lisboa e Benfica", id: 1903 },
  { name: "Sporting Clube de Braga", id: 5613 },
  { name: "FC Paços de Ferreira", id: 507 },
  { name: "Vitória SC", id: 5543 },
  { name: "CD Santa Clara", id: 5530 },
  { name: "Os Belenenses Futebol", id: 5568 },
  { name: "Moreirense FC", id: 583 },
  { name: "Gil Vicente FC", id: 5533 },
  { name: "CD Tondela", id: 1049 },
  { name: "Portimonense SC", id: 5601 },
  { name: "CS Marítimo", id: 5575 },
  { name: "FC Famalicão", id: 5531 },
  { name: "Rio Ave FC", id: 496 },
  { name: "Boavista FC", id: 810 },
  { name: "SC Farense", id: 5602 },
  { name: "CD Nacional", id: 5529 },
  { name: "AFC Ajax", id: 678 },
  { name: "PSV", id: 674 },
  { name: "AZ", id: 682 },
  { name: "SBV Vitesse", id: 679 },
  { name: "Feyenoord Rotterdam", id: 675 },
  { name: "FC Utrecht", id: 676 },
  { name: "FC Groningen", id: 677 },
  { name: "Sparta Rotterdam", id: 6806 },
  { name: "Heracles Almelo", id: 671 },
  { name: "Fortuna Sittard", id: 1920 },
  { name: "SC Heerenveen", id: 673 },
  { name: "FC Twente '65", id: 666 },
  { name: "PEC Zwolle", id: 684 },
  { name: "RKC Waalwijk", id: 683 },
  { name: "Willem II Tilburg", id: 672 },
  { name: "FC Emmen", id: 1914 },
  { name: "VVV Venlo", id: 668 },
  { name: "ADO Den Haag", id: 680 },
  { name: "Norwich City FC", id: 68 },
  { name: "Watford FC", id: 346 },
  { name: "Brentford FC", id: 402 },
  { name: "Swansea City AFC", id: 72 },
  { name: "AFC Bournemouth", id: 1044 },
  { name: "Barnsley FC", id: 357 },
  { name: "Reading FC", id: 355 },
  { name: "Cardiff City FC", id: 715 },
  { name: "Queens Park Rangers FC", id: 69 },
  { name: "Middlesbrough FC", id: 343 },
  { name: "Millwall FC", id: 384 },
  { name: "Luton Town FC", id: 389 },
  { name: "Preston North End FC", id: 1081 },
  { name: "Stoke City FC", id: 70 },
  { name: "Blackburn Rovers FC", id: 59 },
  { name: "Nottingham Forest FC", id: 351 },
  { name: "Coventry City FC", id: 1076 },
  { name: "Birmingham City FC", id: 332 },
  { name: "Bristol City FC", id: 387 },
  { name: "Huddersfield Town AFC", id: 394 },
  { name: "Sheffield Wednesday FC", id: 345 },
  { name: "Derby County FC", id: 342 },
  { name: "Rotherham United FC", id: 385 },
  { name: "Wycombe Wanderers FC", id: 1146 },
];
